### ISSUE TITLE
any way to get samples from applications that require remote-write?

### ISSUE THREAD

**Issue by parkedwards** [GoogleCloudPlatform/prometheus-engine#477] opened 2023-05-16 15:36 UTC
hey there,

we're currently exploring adding new 3rd party applications to our stack, and those applications can only emit metric samples through [prometheus remote-write](https://prometheus.io/docs/practices/remote_write/)

just want to make sure i'm not missing anything, but this [section in the docs](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-unmanaged#:~:text=Managed%20Service%20for%20Prometheus%20does,filters%20and%20local%20aggregations.) suggests there's no existing support for getting such metrics into GMP / Monarch. 

> Managed Service for Prometheus does not support exporting metrics from a federation server or from a server used as a remote-write receiver. You can replicate all federation server functionality, including reducing ingestion volume by aggregating data before sending to Monarch, by using [filters](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-unmanaged#filter-metrics) and [local aggregations](https://cloud.google.com/stackdriver/docs/managed-prometheus/cost-controls#local-aggregation).

is that definitely the case at the moment?  thanks in advance!

**Comment by lyanco** [comment] 2023-05-17 15:51
If you are only exporting gauges and counters, then remote writing to a local Prometheus which forwards the data to the server might work, although it would cost 2x as much as expected (remote write strips TYPE, so if we see an untyped metric, we write it as both a gauge and a counter). If your 3rd party app exports histograms or summaries, then this won't work.

Which applications are you using that only support remote write?

**Comment by pintohutch** [comment] 2023-05-17 20:25
Duplicate of #427

**Closed as not planned by pintohutch** 2023-05-17 20:25 UTC

**Comment by parkedwards** [comment] 2023-05-26 16:46
thanks all - @lyanco to answer your question, this application is Grafana Tempo.  Tempo collects distributed tracing spans, but also needs to write the metrics in Prometheus format, which it appears to only do so through remote-write

**Comment by lyanco** [comment] 2023-05-26 17:09
Ack - I've heard this use case before, and agreed there seems to be no way to do it without Remote Write. Thanks for the context.
