### ISSUE TITLE
PodMonitoring resource doesn't collect metrics for Google Cloud Monitoring

### ISSUE THREAD

**Issue by NibiruHeisenberg** [GoogleCloudPlatform/prometheus-engine#359] opened 2022-11-05 03:25 UTC
Hi, I followed the steps at https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#gmp-pod-monitoring to deploy the example app and PodMonitoring resource example to my Autopilot GKE cluster. The GKE cluster came with Managed Service for Prometheus enabled and is running 1.24.4-gke.800.

I applied the example app deployment by running

```sh
kubectl -n default apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/prometheus-engine/v0.5.0/examples/example-app.yaml
```

and then the PodMonitoring resource via

```sh
kubectl -n default apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/prometheus-engine/v0.5.0/examples/pod-monitoring.yaml
```

Note that they are both in the same `default` namespace.

I searched for metrics in Google Cloud Monitoring but couldn't find any metrics related to this pod. Could there perhaps be some error in the ingestion?

**Comment by lyanco** [comment] 2022-11-07 20:18
Please see https://github.com/GoogleCloudPlatform/prometheus-engine/issues/300 - currently Autopilot doesn't work with GMP but we're targeting 1.25 and 1.24 support pretty soon.

**Comment by pintohutch** [comment] 2022-11-11 16:06
As an FYI @NibiruHeisenberg you shouldn't need to mess with workload identity if enabling in GKE.

As Lee said, we're working on Autopilot support on 1.24+ clusters. I'm going to close this as a duplicate of #300 for now.

Please reach out if you have any other Autopilot issues there.

**Closed** 2022-11-11 16:07 UTC

**Comment by lyanco** [comment] 2023-01-04 17:25
FYI GMP now working in AP clusters running 1.25+. See https://github.com/GoogleCloudPlatform/prometheus-engine/issues/300 for details.
